/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feeds */
        get: operations["list_feeds_api_v1_feeds_get"];
        put?: never;
        /** Create Feed */
        post: operations["create_feed_api_v1_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feed Health */
        get: operations["list_feed_health_api_v1_feeds_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Feed */
        post: operations["ingest_feed_api_v1_feeds__feed_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Feed Folder */
        patch: operations["assign_feed_folder_api_v1_feeds__feed_id__folder_patch"];
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feed Settings */
        patch: operations["update_feed_settings_api_v1_feeds__feed_id__settings_patch"];
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feed Lifecycle */
        patch: operations["update_feed_lifecycle_api_v1_feeds__feed_id__lifecycle_patch"];
        trace?: never;
    };
    "/api/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_api_v1_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_v1_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["delete_folder_api_v1_folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Update Folder */
        patch: operations["update_folder_api_v1_folders__folder_id__patch"];
        trace?: never;
    };
    "/api/v1/articles/filter-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filter Preview */
        post: operations["filter_preview_api_v1_articles_filter_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_v1_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/state/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Patch Article State */
        post: operations["bulk_patch_article_state_api_v1_articles_state_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/state/mark-scope-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Scope As Read */
        post: operations["mark_scope_as_read_api_v1_articles_state_mark_scope_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_v1_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}/fulltext/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch Article Fulltext */
        post: operations["fetch_article_fulltext_api_v1_articles__article_id__fulltext_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Article State */
        patch: operations["patch_article_state_api_v1_articles__article_id__state_patch"];
        trace?: never;
    };
    "/api/v1/imports/opml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Opml */
        post: operations["import_opml_api_v1_imports_opml_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_v1_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streams */
        get: operations["list_streams_api_v1_streams_get"];
        put?: never;
        /** Create Stream */
        post: operations["create_stream_api_v1_streams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Stream */
        delete: operations["delete_stream_api_v1_streams__stream_id__delete"];
        options?: never;
        head?: never;
        /** Update Stream */
        patch: operations["update_stream_api_v1_streams__stream_id__patch"];
        trace?: never;
    };
    "/api/v1/streams/{stream_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stream Articles */
        get: operations["list_stream_articles_api_v1_streams__stream_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{stream_id}/classifier-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stream Classifier Runs */
        get: operations["list_stream_classifier_runs_api_v1_streams__stream_id__classifier_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{stream_id}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stream Backfill */
        post: operations["run_stream_backfill_api_v1_streams__stream_id__backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigation */
        get: operations["get_navigation_api_v1_navigation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plugin Areas */
        get: operations["list_plugin_areas_api_v1_plugins_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plugin Status */
        get: operations["list_plugin_status_api_v1_plugins_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleDetailOut */
        ArticleDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Feed Id */
            feed_id: string | null;
            /** Feed Title */
            feed_title: string | null;
            /** Source Id */
            source_id: string;
            /** Canonical Url */
            canonical_url: string | null;
            /** Title */
            title: string;
            /** Content Text */
            content_text: string;
            /** Language */
            language: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Read */
            is_read: boolean;
            /** Is Starred */
            is_starred: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Stream Ids */
            stream_ids?: string[];
            /** Stream Match Reasons */
            stream_match_reasons?: {
                [key: string]: string;
            } | null;
            /** Stream Match Evidence */
            stream_match_evidence?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /**
             * Fulltext Status
             * @default idle
             * @enum {string}
             */
            fulltext_status: "idle" | "pending" | "succeeded" | "failed";
            /** Fulltext Error */
            fulltext_error?: string | null;
            /** Fulltext Fetched At */
            fulltext_fetched_at?: string | null;
            /** Fulltext Content Text */
            fulltext_content_text?: string | null;
            /** Fulltext Content Html */
            fulltext_content_html?: string | null;
            /**
             * Content Source
             * @default feed_excerpt
             * @enum {string}
             */
            content_source: "feed_excerpt" | "full_article";
        };
        /** ArticleFulltextFetchOut */
        ArticleFulltextFetchOut: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "pending" | "succeeded" | "failed";
            /** Error Message */
            error_message?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /**
             * Content Source
             * @enum {string}
             */
            content_source: "feed_excerpt" | "full_article";
        };
        /** ArticleListItemOut */
        ArticleListItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Feed Id */
            feed_id: string | null;
            /** Feed Title */
            feed_title: string | null;
            /** Title */
            title: string;
            /** Canonical Url */
            canonical_url: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Read */
            is_read: boolean;
            /** Is Starred */
            is_starred: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Stream Ids */
            stream_ids?: string[];
            /** Stream Match Reasons */
            stream_match_reasons?: {
                [key: string]: string;
            } | null;
            /** Stream Match Evidence */
            stream_match_evidence?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
        };
        /** ArticleListResponse */
        ArticleListResponse: {
            /** Items */
            items: components["schemas"]["ArticleListItemOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ArticleOut */
        ArticleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Feed Id */
            feed_id: string | null;
            /** Source Id */
            source_id: string;
            /** Canonical Url */
            canonical_url: string | null;
            /** Title */
            title: string;
            /** Content Text */
            content_text: string;
            /** Language */
            language: string | null;
            /** Published At */
            published_at: string | null;
            /** Duplicate Of Id */
            duplicate_of_id: string | null;
            /** Dedup Confidence */
            dedup_confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ArticleScopeReadPatch */
        ArticleScopeReadPatch: {
            /**
             * Scope Type
             * @default system
             * @enum {string}
             */
            scope_type: "system" | "folder" | "feed" | "stream";
            /** Scope Id */
            scope_id?: string | null;
            /**
             * State
             * @default all
             * @enum {string}
             */
            state: "all" | "unread" | "saved" | "archived" | "fresh" | "recent";
            /** Q */
            q?: string | null;
        };
        /** ArticleStateBulkPatch */
        ArticleStateBulkPatch: {
            /** Article Ids */
            article_ids: string[];
            /** Is Read */
            is_read?: boolean | null;
            /** Is Starred */
            is_starred?: boolean | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /** ArticleStateOut */
        ArticleStateOut: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Is Read */
            is_read: boolean;
            /** Is Starred */
            is_starred: boolean;
            /** Is Archived */
            is_archived: boolean;
        };
        /** ArticleStatePatch */
        ArticleStatePatch: {
            /** Is Read */
            is_read?: boolean | null;
            /** Is Starred */
            is_starred?: boolean | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /** AuthLoginRequest */
        AuthLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** AuthRegisterRequest */
        AuthRegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /** Body_import_opml_api_v1_imports_opml_post */
        Body_import_opml_api_v1_imports_opml_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** DashboardCardAvailabilityOut */
        DashboardCardAvailabilityOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable" | "degraded";
            /** Reason */
            reason?: string | null;
            /** Dependency Spec */
            dependency_spec?: string | null;
        };
        /** DashboardSummaryOut */
        DashboardSummaryOut: {
            /** Cards */
            cards: components["schemas"]["DashboardCardAvailabilityOut"][];
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
        };
        /** FeedCreate */
        FeedCreate: {
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Site Url */
            site_url?: string | null;
            /** Folder Id */
            folder_id?: string | null;
        };
        /** FeedFolderAssignmentUpdate */
        FeedFolderAssignmentUpdate: {
            /** Folder Id */
            folder_id: string | null;
        };
        /** FeedFolderCreate */
        FeedFolderCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Sort Order
             * @default 100
             */
            sort_order: number;
        };
        /** FeedFolderOut */
        FeedFolderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedFolderUpdate */
        FeedFolderUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** FeedHealthItemOut */
        FeedHealthItemOut: {
            /**
             * Feed Id
             * Format: uuid
             */
            feed_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Site Url */
            site_url: string | null;
            /** Folder Id */
            folder_id: string | null;
            /**
             * Lifecycle Status
             * @enum {string}
             */
            lifecycle_status: "active" | "paused" | "archived";
            /** Fetch Interval Minutes */
            fetch_interval_minutes: number;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Last Fetch Success At */
            last_fetch_success_at: string | null;
            /** Last Fetch Error */
            last_fetch_error: string | null;
            /** Last Fetch Error At */
            last_fetch_error_at: string | null;
            /** Is Stale */
            is_stale: boolean;
            /** Stale Age Hours */
            stale_age_hours: number | null;
            /** Articles Last 7D */
            articles_last_7d: number;
            /** Estimated Articles Per Day 7D */
            estimated_articles_per_day_7d: number;
            /** Unread Count */
            unread_count: number;
        };
        /** FeedHealthListResponse */
        FeedHealthListResponse: {
            /** Items */
            items: components["schemas"]["FeedHealthItemOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            summary: components["schemas"]["FeedHealthSummaryOut"];
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
        };
        /** FeedHealthSummaryOut */
        FeedHealthSummaryOut: {
            /** Total Feed Count */
            total_feed_count: number;
            /** Active Feed Count */
            active_feed_count: number;
            /** Paused Feed Count */
            paused_feed_count: number;
            /** Archived Feed Count */
            archived_feed_count: number;
            /** Stale Feed Count */
            stale_feed_count: number;
            /** Error Feed Count */
            error_feed_count: number;
        };
        /** FeedIngestResult */
        FeedIngestResult: {
            /**
             * Feed Id
             * Format: uuid
             */
            feed_id: string;
            /**
             * Fetched Count
             * @default 0
             */
            fetched_count: number;
            /**
             * Inserted Count
             * @default 0
             */
            inserted_count: number;
            /**
             * Duplicate Count
             * @default 0
             */
            duplicate_count: number;
            /**
             * Canonical Duplicate Count
             * @default 0
             */
            canonical_duplicate_count: number;
            /**
             * Filtered Count
             * @default 0
             */
            filtered_count: number;
            /**
             * Stream Match Count
             * @default 0
             */
            stream_match_count: number;
            /**
             * Plugin Processed Count
             * @default 0
             */
            plugin_processed_count: number;
            /** Errors */
            errors?: string[];
        };
        /** FeedLifecycleResultOut */
        FeedLifecycleResultOut: {
            feed: components["schemas"]["FeedOut"];
            /** Marked Read Count */
            marked_read_count: number;
        };
        /** FeedLifecycleUpdate */
        FeedLifecycleUpdate: {
            /**
             * Action
             * @enum {string}
             */
            action: "pause" | "resume" | "archive" | "unarchive";
        };
        /** FeedOut */
        FeedOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Id */
            owner_id: string | null;
            /** Folder Id */
            folder_id: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Site Url */
            site_url: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Archived At */
            archived_at: string | null;
            /** Fetch Interval Minutes */
            fetch_interval_minutes: number;
            /** Etag */
            etag: string | null;
            /** Last Modified */
            last_modified: string | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Last Fetch Success At */
            last_fetch_success_at: string | null;
            /** Last Fetch Error */
            last_fetch_error: string | null;
            /** Last Fetch Error At */
            last_fetch_error_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedSettingsUpdate */
        FeedSettingsUpdate: {
            /** Fetch Interval Minutes */
            fetch_interval_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRuleCreate */
        IngestRuleCreate: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /** Include Keywords */
            include_keywords?: string[];
            /** Exclude Keywords */
            exclude_keywords?: string[];
            /** Source Contains */
            source_contains?: string | null;
            /** Language Equals */
            language_equals?: string | null;
            /**
             * Action
             * @default drop
             * @constant
             */
            action: "drop";
        };
        /** IngestRuleOut */
        IngestRuleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            /** Priority */
            priority: number;
            /** Include Keywords */
            include_keywords: string[];
            /** Exclude Keywords */
            exclude_keywords: string[];
            /** Source Contains */
            source_contains: string | null;
            /** Language Equals */
            language_equals: string | null;
            /**
             * Action
             * @constant
             */
            action: "drop";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IngestRuleUpdate */
        IngestRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Priority */
            priority?: number | null;
            /** Include Keywords */
            include_keywords?: string[] | null;
            /** Exclude Keywords */
            exclude_keywords?: string[] | null;
            /** Source Contains */
            source_contains?: string | null;
            /** Language Equals */
            language_equals?: string | null;
            /** Action */
            action?: "drop" | null;
        };
        /** KeywordFilterPreviewRequest */
        KeywordFilterPreviewRequest: {
            /** Include Keywords */
            include_keywords?: string[];
            /** Exclude Keywords */
            exclude_keywords?: string[];
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** KeywordStreamCreate */
        KeywordStreamCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /** Match Query */
            match_query?: string | null;
            /** Include Keywords */
            include_keywords?: string[];
            /** Exclude Keywords */
            exclude_keywords?: string[];
            /** Include Regex */
            include_regex?: string[];
            /** Exclude Regex */
            exclude_regex?: string[];
            /** Source Contains */
            source_contains?: string | null;
            /** Language Equals */
            language_equals?: string | null;
            /**
             * Classifier Mode
             * @default rules_only
             * @enum {string}
             */
            classifier_mode: "rules_only" | "classifier_only" | "hybrid";
            /** Classifier Plugin */
            classifier_plugin?: string | null;
            /** Classifier Config */
            classifier_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Classifier Min Confidence
             * @default 0.7
             */
            classifier_min_confidence: number;
        };
        /** KeywordStreamOut */
        KeywordStreamOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Folder Id */
            folder_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Priority */
            priority: number;
            /** Match Query */
            match_query: string | null;
            /** Include Keywords */
            include_keywords: string[];
            /** Exclude Keywords */
            exclude_keywords: string[];
            /** Include Regex */
            include_regex: string[];
            /** Exclude Regex */
            exclude_regex: string[];
            /** Source Contains */
            source_contains: string | null;
            /** Language Equals */
            language_equals: string | null;
            /**
             * Classifier Mode
             * @enum {string}
             */
            classifier_mode: "rules_only" | "classifier_only" | "hybrid";
            /** Classifier Plugin */
            classifier_plugin: string | null;
            /** Classifier Config */
            classifier_config: {
                [key: string]: unknown;
            };
            /** Classifier Min Confidence */
            classifier_min_confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KeywordStreamUpdate */
        KeywordStreamUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Priority */
            priority?: number | null;
            /** Match Query */
            match_query?: string | null;
            /** Include Keywords */
            include_keywords?: string[] | null;
            /** Exclude Keywords */
            exclude_keywords?: string[] | null;
            /** Include Regex */
            include_regex?: string[] | null;
            /** Exclude Regex */
            exclude_regex?: string[] | null;
            /** Source Contains */
            source_contains?: string | null;
            /** Language Equals */
            language_equals?: string | null;
            /** Classifier Mode */
            classifier_mode?: ("rules_only" | "classifier_only" | "hybrid") | null;
            /** Classifier Plugin */
            classifier_plugin?: string | null;
            /** Classifier Config */
            classifier_config?: {
                [key: string]: unknown;
            } | null;
            /** Classifier Min Confidence */
            classifier_min_confidence?: number | null;
        };
        /** NavigationFeedNodeOut */
        NavigationFeedNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Unread Count */
            unread_count: number;
        };
        /** NavigationFolderNodeOut */
        NavigationFolderNodeOut: {
            /** Id */
            id: string | null;
            /** Name */
            name: string;
            /** Unread Count */
            unread_count: number;
            /** Feeds */
            feeds?: components["schemas"]["NavigationFeedNodeOut"][];
        };
        /** NavigationStreamNodeOut */
        NavigationStreamNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Folder Id */
            folder_id?: string | null;
            /** Unread Count */
            unread_count: number;
        };
        /** NavigationSystemNodeOut */
        NavigationSystemNodeOut: {
            /**
             * Key
             * @enum {string}
             */
            key: "all" | "fresh" | "saved" | "archived" | "recent";
            /** Title */
            title: string;
            /** Unread Count */
            unread_count: number;
        };
        /** NavigationTreeOut */
        NavigationTreeOut: {
            /** Systems */
            systems: components["schemas"]["NavigationSystemNodeOut"][];
            /** Folders */
            folders: components["schemas"]["NavigationFolderNodeOut"][];
            /** Streams */
            streams: components["schemas"]["NavigationStreamNodeOut"][];
        };
        /** OpmlImportEntryResult */
        OpmlImportEntryResult: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "skipped_existing" | "skipped_conflict" | "invalid" | "duplicate_in_file";
            /** Reason */
            reason?: string | null;
        };
        /** OpmlImportResult */
        OpmlImportResult: {
            /**
             * Total Entries
             * @default 0
             */
            total_entries: number;
            /**
             * Unique Urls
             * @default 0
             */
            unique_urls: number;
            /**
             * Created Count
             * @default 0
             */
            created_count: number;
            /**
             * Skipped Existing Count
             * @default 0
             */
            skipped_existing_count: number;
            /**
             * Skipped Conflict Count
             * @default 0
             */
            skipped_conflict_count: number;
            /**
             * Invalid Count
             * @default 0
             */
            invalid_count: number;
            /**
             * Duplicate In File Count
             * @default 0
             */
            duplicate_in_file_count: number;
            /** Results */
            results?: components["schemas"]["OpmlImportEntryResult"][];
            /** Errors */
            errors?: string[];
        };
        /** PluginAreaOut */
        PluginAreaOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Icon */
            icon?: string | null;
            /**
             * Order
             * @default 100
             */
            order: number;
            /** Route Key */
            route_key: string;
        };
        /** PluginCapabilityRuntimeCountersOut */
        PluginCapabilityRuntimeCountersOut: {
            /** Success Count */
            success_count: number;
            /** Failure Count */
            failure_count: number;
            /** Timeout Count */
            timeout_count: number;
        };
        /** PluginStatusOut */
        PluginStatusOut: {
            /** Plugin Id */
            plugin_id: string;
            /** Enabled */
            enabled: boolean;
            /** Loaded */
            loaded: boolean;
            /** Capabilities */
            capabilities: string[];
            /** Startup Validation Status */
            startup_validation_status: string;
            /** Last Error */
            last_error: string | null;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Runtime Counters */
            runtime_counters: {
                [key: string]: components["schemas"]["PluginCapabilityRuntimeCountersOut"];
            };
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
        };
        /** StreamArticleOut */
        StreamArticleOut: {
            /**
             * Matched At
             * Format: date-time
             */
            matched_at: string;
            /** Match Reason */
            match_reason?: string | null;
            /** Match Evidence */
            match_evidence?: {
                [key: string]: unknown;
            } | null;
            article: components["schemas"]["ArticleOut"];
        };
        /** StreamBackfillResultOut */
        StreamBackfillResultOut: {
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Scanned Count */
            scanned_count: number;
            /** Previous Match Count */
            previous_match_count: number;
            /** Matched Count */
            matched_count: number;
        };
        /** StreamClassifierRunOut */
        StreamClassifierRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Feed Id */
            feed_id: string | null;
            /**
             * Classifier Mode
             * @enum {string}
             */
            classifier_mode: "classifier_only" | "hybrid";
            /** Plugin Name */
            plugin_name: string;
            /** Provider */
            provider: string | null;
            /** Model Name */
            model_name: string | null;
            /** Model Version */
            model_version: string | null;
            /** Matched */
            matched: boolean;
            /** Confidence */
            confidence: number | null;
            /** Threshold */
            threshold: number;
            /** Reason */
            reason: string | null;
            /**
             * Run Status
             * @enum {string}
             */
            run_status: "ok" | "no_decision";
            /** Error Message */
            error_message: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryOut"];
                };
            };
        };
    };
    list_feeds_api_v1_feeds_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feed_api_v1_feeds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feed_health_api_v1_feeds_health_get: {
        parameters: {
            query?: {
                lifecycle?: "all" | "active" | "paused" | "archived";
                q?: string | null;
                stale_only?: boolean;
                error_only?: boolean;
                all?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealthListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_feed_api_v1_feeds__feed_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_feed_folder_api_v1_feeds__feed_id__folder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedFolderAssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feed_settings_api_v1_feeds__feed_id__settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feed_lifecycle_api_v1_feeds__feed_id__lifecycle_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedLifecycleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedLifecycleResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_api_v1_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedFolderOut"][];
                };
            };
        };
    };
    create_folder_api_v1_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedFolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedFolderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_v1_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_api_v1_folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedFolderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedFolderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filter_preview_api_v1_articles_filter_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordFilterPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_v1_articles_get: {
        parameters: {
            query?: {
                scope_type?: "system" | "folder" | "feed" | "stream";
                scope_id?: string | null;
                state?: "all" | "unread" | "saved" | "archived" | "fresh" | "recent";
                q?: string | null;
                limit?: number;
                offset?: number;
                sort?: "newest" | "oldest" | "unread_first";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_patch_article_state_api_v1_articles_state_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleStateBulkPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_scope_as_read_api_v1_articles_state_mark_scope_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleScopeReadPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_v1_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_article_fulltext_api_v1_articles__article_id__fulltext_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleFulltextFetchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_article_state_api_v1_articles__article_id__state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleStatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_opml_api_v1_imports_opml_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_opml_api_v1_imports_opml_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpmlImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRuleOut"][];
                };
            };
        };
    };
    create_rule_api_v1_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_streams_api_v1_streams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordStreamOut"][];
                };
            };
        };
    };
    create_stream_api_v1_streams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordStreamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordStreamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stream_api_v1_streams__stream_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stream_api_v1_streams__stream_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordStreamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordStreamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stream_articles_api_v1_streams__stream_id__articles_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamArticleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stream_classifier_runs_api_v1_streams__stream_id__classifier_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamClassifierRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_backfill_api_v1_streams__stream_id__backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamBackfillResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigation_api_v1_navigation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationTreeOut"];
                };
            };
        };
    };
    list_plugin_areas_api_v1_plugins_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginAreaOut"][];
                };
            };
        };
    };
    list_plugin_status_api_v1_plugins_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginStatusOut"][];
                };
            };
        };
    };
}
